version: "3.8"

services:
  postgres:
    container_name: postgressql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "6543:5432"
    hostname: martin_server
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: siddhant.thakur@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass1234
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "8888:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: